version: "3"
volumes:
  db-data:
services:
  db:
    image: mongo
    environment:
      # provide your credentials here
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=rootPass
    volumes:
      - db-data:/data/db
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  notebook:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - PUID=${USER_ID}
    volumes:
      - ./jupyter_home:/home/angel/host_data
    ports:
      - "8885:8888"
    expose:
      - "8885"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
