version: "3"
volumes:
  db-data:
services:
  db:
    image: mongo
    environment:
      # provide your credentials here
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=rootPass
    volumes:
      - db-data:/data/db
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  notebook:
    build:
      context: ./
      dockerfile: Dockerfile
    entrypoint: /bin/bash ./host_data/start-notebook.sh
    volumes:
      - ./jupyter_home:/home/host_data
    ports:
      - "8888:8888"
    expose:
      - "8888"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
